#!/usr/bin/env node
/**
 * Builds src/v3/v3.css, the production V3 stylesheet, from the approved
 * Design Lab sources without the V2 Lab's unused rules.
 *
 * The V3 Lab loads seven stylesheets (design-lab-v2/v2.css and
 * design-lab-v3/v3.css, x.css, site.css, film.css, app.css, surfaces.css).
 * Production keeps every rule whose selector's classes all appear in the
 * production V3 sources (src/v3, the public homepage, the (fs) screens),
 * plus every class the sources build from a prefix (`xs-op-${kind}`), and
 * drops the rest: the V2 Lab's own screens, the V3 Lab's Loyalty
 * simulation, the lab controls. Element, attribute and pseudo selectors
 * without a class are kept. Run after changing any V3 source:
 *
 *   node scripts/v3-css.mjs
 */
import fs from "node:fs";
import path from "node:path";
import postcss from "postcss";

const root = path.resolve(new URL(".", import.meta.url).pathname, "..");
const SOURCES = [
  "src/app/design-lab-v2/v2.css",
  "src/app/design-lab-v3/v3.css",
  "src/app/design-lab-v3/x/x.css",
  "src/app/design-lab-v3/x/site.css",
  "src/app/design-lab-v3/x/film.css",
  "src/app/design-lab-v3/x/app.css",
  "src/app/design-lab-v3/x/surfaces.css",
];
const USED_IN = ["src/v3", "src/app/page.tsx", "src/app/(fs)", "src/components/fs"];
const OUT = "src/v3/v3.css";

function walk(dir, out = []) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) walk(p, out); else if (/\.(tsx?|css)$/.test(e.name) && !p.endsWith(OUT)) out.push(p);
  }
  return out;
}
const files = USED_IN.flatMap((s) => { const p = path.join(root, s); return fs.statSync(p).isDirectory() ? walk(p) : [p]; });
const text = files.map((f) => fs.readFileSync(f, "utf8")).join("\n");
const used = new Set(text.match(/[A-Za-z0-9_-]+/g));
// classes built from a prefix in a template string: `xs-op-${kind}`, `x-fp-still${sel}`
const prefixes = new Set([...text.matchAll(/([A-Za-z0-9_-]+-)\$\{/g)].map((m) => m[1]));
// data attributes and states that the CSS keys on are not classes; only class tokens are checked
const keepClass = (c) => used.has(c) || [...prefixes].some((p) => c.startsWith(p));

const CLASS_RE = /\.(-?[_a-zA-Z]+[_a-zA-Z0-9-]*)/g;
function selectorUsed(sel) {
  // strip pseudo-class arguments that are not class names (:not(.x) still counts as a class the rule keys on)
  const classes = [...sel.matchAll(CLASS_RE)].map((m) => m[1]);
  return classes.every(keepClass);
}

let kept = 0, dropped = 0;
function prune(container) {
  container.each((node) => {
    if (node.type === "rule") {
      const sels = node.selectors.filter(selectorUsed);
      if (sels.length === 0) { dropped++; node.remove(); return; }
      if (sels.length !== node.selectors.length) node.selectors = sels;
      kept++;
    } else if (node.type === "atrule") {
      if (/^(media|supports|layer|container)$/.test(node.name)) { prune(node); if (!node.nodes || node.nodes.length === 0) node.remove(); }
      // keyframes and font-face are kept whole
    } else if (node.type === "comment") node.remove();
  });
}

const parts = [];
for (const s of SOURCES) {
  const css = fs.readFileSync(path.join(root, s), "utf8");
  const ast = postcss.parse(css, { from: s });
  prune(ast);
  parts.push(`/* ---- from ${s} ---- */\n${ast.toString()}`);
}
const header = `/*\n  TapMart V3 production stylesheet. GENERATED by scripts/v3-css.mjs from the\n  approved Design Lab sources; do not edit by hand. Rules are kept only when\n  the production V3 sources use their classes. The V2 tokens are re-pointed\n  to the V3 material system inside (.v3 block); the UI font is the root\n  --font-sans (DM Sans, loaded once in src/app/layout.tsx).\n*/\n.v2 { --v2-font-ui: var(--font-sans); --v2-font-display: var(--font-sans); }\n`;
fs.writeFileSync(path.join(root, OUT), header + parts.join("\n"));
const bytes = fs.statSync(path.join(root, OUT)).size;
console.log(`v3.css: ${kept} rules kept, ${dropped} dropped, ${bytes} bytes, ${used.size} tokens from ${files.length} files`);
