import { chromium } from "playwright-core";
const exe = "/opt/pw-browsers/chromium_headless_shell-1194/chrome-linux/headless_shell";
const b = await chromium.launch({ executablePath: exe });
const p = await b.newPage({ viewport: { width: 1280, height: 800 } });
p.on("console", (m) => { if (m.type() === "error") console.log("console:", m.text().slice(0, 300)); });
await p.goto("http://localhost:3000/sign-in");
await p.fill('input[name=email]', "owner@storeday.test");
await p.fill('input[name=password]', "Password123!");
await p.click('button[type=submit]');
await p.waitForTimeout(8000);
console.log("after login url:", p.url());
const err = await p.locator("p.text-danger, .text-danger").allTextContents();
console.log("errors on page:", err);
await p.screenshot({ path: "/tmp/after-login.png" });
await b.close();
